// errors
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// users
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER';

// Quiz
export const GET_QUIZ = 'GET_QUIZ';
export const SET_QUIZ_LOADING = 'SET_QUIZ_LOADING';
export const SET_ADD_NEW_QUIZ_LOADING = 'SET_ADD_NEW_QUIZ_LOADING';
export const DELETE_QUIZ = 'DELETE_QUIZ';
export const ADD_QUIZ = 'ADD_QUIZ';

// Questions
export const GET_QUESTIONS = 'GET_QUESTIONS';
export const SET_QUESTIONS_LOADING = 'SET_QUESTIONS_LOADING';
export const SET_ADD_NEW_QUESTIONS_LOADING = 'SET_ADD_NEW_QUESTIONS_LOADING';
export const DELETE_QUESTIONS = 'DELETE_QUESTIONS';
export const ADD_QUESTIONS = 'ADD_QUESTIONS';


